FROM alpine AS frostfs-s3-gw
RUN apk add --no-cache bash ca-certificates

WORKDIR /

COPY /bin/frostfs-s3-gw /bin/frostfs-s3-gw
COPY /bin/frostfs-s3-authmate /bin/frostfs-s3-authmate

ENTRYPOINT ["/bin/frostfs-s3-gw"]
